### ISSUE TITLE
Hypergea dependency

### ISSUE THREAD

**Issue by Fred-White94** [eporetsky/MutRank#1]
Hi, I was just wondering if you had plans to replace the bits that depend on hypergea since it is no longer supported by cran - therefore I cannot use mutrank on R4.0.2

**Comment by eporetsky** [comment]
The issue was resolved by adding the archived hypergea 1.3.6 package from CRAN to the MutRank repository. Hypergea will now be installed automatically when running the Shiny app. Let me know if the problem persists.

**Comment by Fred-White94** [comment]
Thanks a lot, works fine now!
